// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyUQb1JEbaPMZLP6utYGqh1JlgZSBRL0I',
    appId: '1:284259483635:web:b50080f7955db4c9715c86',
    messagingSenderId: '284259483635',
    projectId: 'moneybase-bc047',
    authDomain: 'moneybase-bc047.firebaseapp.com',
    storageBucket: 'moneybase-bc047.firebasestorage.app',
    measurementId: 'G-HL4V1CD6PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlSvIofvMWvZ8L1bzYY8jMQCbEoP5YLjo',
    appId: '1:284259483635:android:2e81e8bc1d4d4648715c86',
    messagingSenderId: '284259483635',
    projectId: 'moneybase-bc047',
    storageBucket: 'moneybase-bc047.firebasestorage.app',
  );

  static const String androidServerClientId =
      '284259483635-geruaub92vfh6k2bvp4n9t700cprj6tt.apps.googleusercontent.com';
}
